# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Carl Hauck 
email: carlhauck@t-online.de
description: > # this means to ignore newlines until "baseurl:"
         Welcome! This is my personal site and will be playground and exposé at the same time. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.carlhauck.de" # the base hostname & protocol for your site
twitter_username: carl_hauck
github_username: biocarl

# Build settings
markdown: kramdown
highlighter: pygments
